apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: civoissuer
spec:
  acme:
    email: example@example.com
    privateKeySecretRef:
      name: civio-okteto-enterprise-letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          solverName: "civo"
          groupName: civo.webhook.okteto.com
          config:
            apiKeySecretRef:
              key: key
              name: dns